"""Contact Directory — Juan Pablo Osorio."""
from dataclasses import asdict
import csv
import io
import streamlit as st
from bst import Contact
from benchmark import compare, demo_tree

st.set_page_config(page_title="Contact Directory | Juan Pablo Osorio", page_icon="📇", layout="wide")
st.title("📇 Contact Directory")
st.caption("Assignment 6.1 · Juan Pablo Osorio · A custom Binary Search Tree")
if "tree" not in st.session_state:
    st.session_state.tree = demo_tree()
tree = st.session_state.tree
st.info("Contacts live in your current browser session. Download CSV to keep a copy; a new session starts with fictional sample contacts.")
if "notice" in st.session_state:
    st.success(st.session_state.pop("notice"))
a, b = st.columns(2)
a.metric("Contacts", len(tree))
b.metric("Tree height (levels)", tree.height())

with st.expander("Add a contact", expanded=True):
    with st.form("add", clear_on_submit=True):
        name = st.text_input("Full name")
        phone = st.text_input("Phone")
        email = st.text_input("Email")
        if st.form_submit_button("Add contact", type="primary"):
            try:
                contact = Contact(name, phone, email)
                if tree.insert(contact):
                    st.session_state.pop("comparison", None)
                    st.session_state.notice = f"Added {contact.name}."
                    st.rerun()
                else:
                    st.error("That name already exists. Names are unique, ignoring case and extra spaces.")
            except ValueError as exc:
                st.error(str(exc))

left, right = st.columns(2)
with left:
    st.subheader("Search")
    with st.form("search"):
        query = st.text_input("Exact name", help="Case and extra spaces are ignored.")
        if st.form_submit_button("Find contact"):
            result = tree.search(query)
            if result:
                st.table([asdict(result)])
            else:
                st.warning("Contact not found.")
with right:
    st.subheader("Delete")
    with st.form("delete"):
        delete_name = st.text_input("Name to delete")
        confirm = st.checkbox("Confirm deletion")
        if st.form_submit_button("Delete contact"):
            if not confirm:
                st.warning("Check Confirm deletion first.")
            elif tree.delete(delete_name):
                st.session_state.pop("comparison", None)
                st.session_state.notice = f"Deleted {delete_name.strip()}."
                st.rerun()
            else:
                st.warning("Contact not found.")

st.subheader("Contacts in alphabetical order")
st.caption("Generated by the BST's inorder traversal (left → node → right).")
records = [asdict(contact) for contact in tree.inorder()]
if records:
    st.dataframe(records, hide_index=True, width="stretch")
    csv_buffer = io.StringIO()
    writer = csv.DictWriter(csv_buffer, fieldnames=["name", "phone", "email"])
    writer.writeheader()
    writer.writerows(records)
    st.download_button("Download contacts as CSV", csv_buffer.getvalue(), "contacts.csv", "text/csv")
else:
    st.info("Your directory is empty. Add a contact above.")

st.divider()
st.subheader("BST vs. linear scan")
st.write("Compare exact-name searches over the same contacts currently in this directory.")
with st.expander("Load a larger sample directory"):
    st.caption("Replaces this session's directory with fictional contacts, inserted in a reproducible shuffled order.")
    sample_count = st.selectbox("Sample contacts", [15, 100, 1000, 5000], index=0)
    replace = st.checkbox("Replace my current contacts with sample data")
    if st.button("Load sample directory", disabled=not replace):
        st.session_state.tree = demo_tree(sample_count)
        st.session_state.pop("comparison", None)
        st.session_state.notice = f"Loaded {sample_count:,} sample contacts."
        st.rerun()
st.caption("200 identical queries per method: 100 hits and 100 misses; 5 trials, alternating method order. Setup and correctness checks are outside the timed region.")
if st.button("Run timing comparison", disabled=not len(tree), type="primary"):
    with st.spinner("Measuring both search methods…"):
        st.session_state.comparison = compare(tree)
if "comparison" in st.session_state:
    result = st.session_state.comparison
    st.write(f"{result['contacts']:,} contacts · height {result['height']} · {result['queries']} queries per trial · {result['trials']} trials")
    st.dataframe(result["rows"], hide_index=True, width="stretch")
    st.bar_chart({row["Method"]: row["Median batch (ms)"] for row in result["rows"]}, y_label="Median batch time (ms)")
    st.caption("Per-lookup time is the median batch time divided by 200. Timings vary by hardware, tree shape, and system load; small datasets may favor linear scan.")
st.markdown("**Why the tree shape matters:** search and deletion take O(h), where h is tree height. A balanced shape gives O(log n); this ordinary, unbalanced BST can degrade to O(n). Linear scan is O(n). Inorder listing visits all n contacts in O(n).")
